---

- name: Add Kubernetes APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: true

- name: Add Kubernetes APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'
  become: true

- name: Install kubernetes packages pinned version (Debian/Ubuntu)
  when:
    - kubeletVersion is defined
    - kubeadmVersion is defined
    - kubectlVersion is defined
  apt:
    name: "{{ item }}"
    update_cache: yes
    force: yes
  become: true
  with_items:
    - kubelet={{ kubeletVersion }}
    - kubeadm={{ kubeadmVersion }}
    - kubectl={{ kubectlVersion }}

- name: Install kubernetes packages (Debian/Ubuntu)
  when:
    - kubeletVersion is not defined
    - kubeadmVersion is not defined
    - kubectlVersion is not defined
  apt:
    name: "{{ item }}"
    update_cache: yes
    force: yes
  become: true
  with_items:
    - kubelet
    - kubeadm
    - kubectl
